//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldStarMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string dwallet {
            get {
                return ((string)(this["dwallet"]));
            }
            set {
                this["dwallet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string dexchange {
            get {
                return ((string)(this["dexchange"]));
            }
            set {
                this["dexchange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string ddonation {
            get {
                return ((string)(this["ddonation"]));
            }
            set {
                this["ddonation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string bwallet {
            get {
                return ((string)(this["bwallet"]));
            }
            set {
                this["bwallet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string bexchange {
            get {
                return ((string)(this["bexchange"]));
            }
            set {
                this["bexchange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string bdonation {
            get {
                return ((string)(this["bdonation"]));
            }
            set {
                this["bdonation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a1 {
            get {
                return ((string)(this["a1"]));
            }
            set {
                this["a1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a2 {
            get {
                return ((string)(this["a2"]));
            }
            set {
                this["a2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a3 {
            get {
                return ((string)(this["a3"]));
            }
            set {
                this["a3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a4 {
            get {
                return ((string)(this["a4"]));
            }
            set {
                this["a4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a5 {
            get {
                return ((string)(this["a5"]));
            }
            set {
                this["a5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a6 {
            get {
                return ((string)(this["a6"]));
            }
            set {
                this["a6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a7 {
            get {
                return ((string)(this["a7"]));
            }
            set {
                this["a7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a8 {
            get {
                return ((string)(this["a8"]));
            }
            set {
                this["a8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string lwallet {
            get {
                return ((string)(this["lwallet"]));
            }
            set {
                this["lwallet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string lexchange {
            get {
                return ((string)(this["lexchange"]));
            }
            set {
                this["lexchange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string ldonation {
            get {
                return ((string)(this["ldonation"]));
            }
            set {
                this["ldonation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a9 {
            get {
                return ((string)(this["a9"]));
            }
            set {
                this["a9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a10 {
            get {
                return ((string)(this["a10"]));
            }
            set {
                this["a10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter an Address")]
        public string a11 {
            get {
                return ((string)(this["a11"]));
            }
            set {
                this["a11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""C:\Users\time\Downloads\cgminer-3.7.2-windows (1)\cgminer-3.7.2-windows\cgminer.exe"" --scrypt -I 12 -g 2 -w 256 --gpu-engine 1100 --gpu-memclock 1250 --gpu-powertune 20 --thread-concurrency 16384 --scrypt -o stratum+tcp://lotus.nut2pools.com:5595 -u juju.u -p p")]
        public string mc1 {
            get {
                return ((string)(this["mc1"]));
            }
            set {
                this["mc1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\Users\\time\\Downloads\\cgminer-3.7.2-windows (1)\\cgminer-3.7.2-windows\\cgminer." +
            "exe\" --scrypt -I 12 -g 2 -w 256 --thread-concurrency 8192 -o stratum+tcp://ltc.g" +
            "ive-me-coins.com:3336 -u juju.testworker -p sorivonio!@#^%12231\r\n ")]
        public string mc2 {
            get {
                return ((string)(this["mc2"]));
            }
            set {
                this["mc2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\Users\\time\\Downloads\\cgminer-3.7.2-windows (1)\\cgminer-3.7.2-windows\\cgminer." +
            "exe\" --scrypt -I 12 -g 2 -w 256 --thread-concurrency 8192 -o stratum+tcp://strat" +
            "um3.dogehouse.org:8080 -u juju.jujuwork -p sorivonio!@#^%12231")]
        public string mc3 {
            get {
                return ((string)(this["mc3"]));
            }
            set {
                this["mc3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\Users\\time\\Downloads\\cgminer-3.7.2-windows (1)\\cgminer-3.7.2-windows\\cgminer." +
            "exe\" --scrypt -I 12 -g 2 -w 256 --gpu-engine 1100 --gpu-memclock 1250 --gpu-powe" +
            "rtune 20 --thread-concurrency 16384 -o stratum+tcp://smc.hash.so:3363 -u juju.u " +
            "-p p")]
        public string mc4 {
            get {
                return ((string)(this["mc4"]));
            }
            set {
                this["mc4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""C:\Users\time\Downloads\cgminer-3.7.2-windows (1)\cgminer-3.7.2-windows\cgminer.exe"" --scrypt -I 12 -g 2 -w 256 --gpu-engine 1100 --gpu-memclock 1250 --gpu-powertune 20 --thread-concurrency 16384 --scrypt -o stratum+tcp://fed.notnull.org:3333 -u juju.u -p p")]
        public string mc5 {
            get {
                return ((string)(this["mc5"]));
            }
            set {
                this["mc5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""C:\Users\time\Downloads\cgminer-3.7.2-windows (1)\cgminer-3.7.2-windows\cgminer.exe"" --scrypt -I 12 -g 2 -w 256 --gpu-engine 1100 --gpu-memclock 1250 --gpu-powertune 20 --thread-concurrency 16384 -o stratum+tcp://pool1.cryptopoolmining.com:4488 -u juju.jujuwork -p sorivonio!@#^%12231")]
        public string mc6 {
            get {
                return ((string)(this["mc6"]));
            }
            set {
                this["mc6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""C:\Users\time\Downloads\cgminer-3.7.2-windows (1)\cgminer-3.7.2-windows\cgminer.exe"" --scrypt -I 12 -g 2 -w 256 --gpu-engine 1100 --gpu-memclock 1250 --gpu-powertune 20 --thread-concurrency 16384 -o stratum+tcp://coinotron.com:3337 -u juju.jujuwork -p pass")]
        public string mc7 {
            get {
                return ((string)(this["mc7"]));
            }
            set {
                this["mc7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\Users\\time\\Downloads\\cgminer-3.7.2-windows (1)\\cgminer-3.7.2-windows\\cgminer." +
            "exe\" --scrypt -I 12 -g 2 -w 256 --thread-concurrency 16384 -o stratum+tcp://coin" +
            "miner.net:19996 -u UiUUtpP8kcgS94mJiQPQst6H7ogWWw4ZPY -p x --queue 0 -s 1")]
        public string mc8 {
            get {
                return ((string)(this["mc8"]));
            }
            set {
                this["mc8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lottocoin")]
        public string mcn1 {
            get {
                return ((string)(this["mcn1"]));
            }
            set {
                this["mcn1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Litecoin")]
        public string mcn2 {
            get {
                return ((string)(this["mcn2"]));
            }
            set {
                this["mcn2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dogecoin")]
        public string mcn3 {
            get {
                return ((string)(this["mcn3"]));
            }
            set {
                this["mcn3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Smartcoin")]
        public string mcn4 {
            get {
                return ((string)(this["mcn4"]));
            }
            set {
                this["mcn4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fedoracoin")]
        public string mcn5 {
            get {
                return ((string)(this["mcn5"]));
            }
            set {
                this["mcn5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nutcoin")]
        public string mcn6 {
            get {
                return ((string)(this["mcn6"]));
            }
            set {
                this["mcn6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Feathercoin")]
        public string mcn7 {
            get {
                return ((string)(this["mcn7"]));
            }
            set {
                this["mcn7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Coino")]
        public string mcn8 {
            get {
                return ((string)(this["mcn8"]));
            }
            set {
                this["mcn8"] = value;
            }
        }
    }
}
